### PR TITLE
Added user story takeaways along with a Kanban Whiteboard

### PR DESCRIPTION
**Pull request by vnvemuri**
Contains information about user stories and whiteboard.
Please review and provide comments for improvement if any

### CODE REVIEW

**Comment by vnvemuri** [comment]
@ggallicc @bwromanski I have incorporated both you requests into my file.
Please review so I can merge.

**Comment by ggallicc** [comment]
OK for me! :+1:

**Comment by vnvemuri** [comment]
@bwromanski @oschulze Can you give me your :+1: as well ?

**Comment by oschulze** [comment]
go for it

**Pull request merged**
